apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-halohalo.name" . }}
  labels:
    {{- include "dev-halohalo.labels" . | nindent 4 }}
  namespace: dev
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.port | quote }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "dev-halohalo.selectorLabels" . | nindent 4 }}
